# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43ee126d9b6ea2220216993a47e7542d176819549be96993b2ee2a9fde84d29a0b6ea6306d65e1061f6edc744abb4ec34ee83f61aaafa073d4358c69fc2cf7e4

test:
  secret_key_base: bdb0b4ce2682b3407a5e26f8ede8761ba99fbebac5475ae18fe51ffb53abba4d87c82052b1e96a3cf63276ff5e246aea26d1cfff49e389d162b2e77ea584bd7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
